runtime: nodejs20
env: standard

# handlers:
#   - url: /(.*\.(html|css|js|ico|jpg|jpeg|png|svg|json|woff|woff2|ttf|eot))$
#     static_files: dist/web-frontend-kk\1
#     upload: dist/web-frontend-kk/(.*\.(html|css|js|ico|jpg|jpeg|png|svg|json|woff|woff2|ttf|eot))$
#     # secure: always

#   - url: /.*
#     script: auto
#     # secure: always
